#Question 2

Using only numpy, implement the function maxpooling2d. It takes as input input_mat and s and outputs output_mat. The variables input_mat and output_mat are square matrices and s is an integer. It should compute the maxpooling operation on input_mat using window of shape s times s.

Source: https://stackoverflow.com/questions/54962004/implement-max-mean-poolingwith-stride-with-numpy

In [0]:
import numpy as np

def maxpooling2d(input_mat, s):
  matrix = input_mat

  if (matrix.shape[0] != matrix.shape[1]):
      if (matrix.shape[0] > matrix.shape[1]):
        while (matrix.shape[1] != matrix.shape[0]):
          zeroes = np.zeros((math.shape[0]), 1)
          matrix = np.append(matrix, zeroes, 1)

      else:
        while (matrix.shape[0] != matrix.shape[1]):
          zeroes = np.zeros((1, matrix.shape[1]))
          matrix = np.append(matrix, zeroes, 0)
  
  out_shape = ((matrix.shape[0] - s)//2 + 1, (matrix.shape[1] - s)//2 + 1)

  s_size = (s, s)

  Mat_w = np.lib.stride_tricks.as_strided(matrix, shape = out_shape + s_size, strides = (2 * matrix.strides[0], 2 * matrix.strides[1]) + matrix.strides)
  Mat_w = Mat_w.reshape(-1, *s_size)

  return Mat_w.max(axis=(1,2)).reshape(out_shape)

#Test Case Output

In [4]:
import skimage.measure

input_mat = []
expected_mat = []
s = []
input_mat.append(np.array([[1, 2, 1, 2],
                      [2, 4, 2, 1],
                      [1, 2, 4, 2],
                      [2, 1, 2, 1]]))
s.append(2)

expected_mat.append(np.array([[4, 2],
                                [2, 4]]))

input_mat.append(np.array([[1, 2, 1, 2, 4, 5],
                      [2, 4, 2, 1, 0, 3],
                      [1, 2, 4, 2, 4, 5],
                      [2, 1, 2, 1, 2, 1],
                      [1, 1, 2, 3, 1, 2],
                      [1, 1, 2, 3, 1, 2]]))
s.append(2)

expected_mat.append([[4, 2, 5],
 [2, 4, 5],
 [1, 3, 2]])


for i in range(len(input_mat)):
  # uncomment top line and comment second line to test code
  output_mat = maxpooling2d(input_mat[i], s[i])
  output_mat = skimage.measure.block_reduce(input_mat[i], (s[i],s[i]), np.max)

  print(output_mat)

  if np.array_equal(output_mat, expected_mat[i]):
    print("Correct output!")
  else:
    print("Incorrect output!")


[[4 2]
 [2 4]]
Correct output!
[[4 2 5]
 [2 4 5]
 [1 3 2]]
Correct output!
